#version: '3.8'
#services:
#  postgres:
#    image: postgres:15
#    container_name: user-service-db
#    environment:
#      POSTGRES_DB: userdb
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"